### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by likui628** [vbenjs/vben3#81]
### Describe the bug

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')    useMenuSetting.ts:34
    at ReactiveEffect.fn (useMenuSetting.ts:34:65)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at get value [as value] (reactivity.esm-bundler.js:1171:39)
    at ReactiveEffect.fn (index.vue:19:23)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at get value [as value] (reactivity.esm-bundler.js:1171:39)
    at unref (reactivity.esm-bundler.js:1074:29)
    at Object.get (reactivity.esm-bundler.js:1077:37)
    at Proxy._sfc_render (index.vue:34:19)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:44)

https://github.com/vbenjs/vben3/blob/d3aa13033202e2fa785f96b12b9887a075ebca46/apps/admin/src/hooks/setting/useMenuSetting.ts#L34

![image](https://github.com/vbenjs/vben3/assets/90845831/42155bdf-20e5-43ca-b76d-c4ca5cc459b5)

### Reproduction

1. clear Application localstorage
2. refresh page
3. user login

## System Info

- Operating System: win 11
- Node version: v16.15.1
- Package manager (npm/yarn/pnpm) and version: pnpm 8.6.12

**Comment by jinmao88** [comment]
src/hooks 在往 @vben\hooks 转移

**Comment by likui628** [comment]
@jinmao88 我来尝试处理下吧

**Comment by MaYaQ** [comment]
> @jinmao88 我来尝试处理下吧
楼主你好 新手有点疑问  我看了下合并请求 没发现有什么改动点

**Comment by likui628** [comment]
> > @jinmao88 我来尝试处理下吧
> > 楼主你好 新手有点疑问  我看了下合并请求 没发现有什么改动点

还没开始，先开个PR占个位

**Comment by aonoa** [comment]
> @jinmao88我来尝试处理下吧

不止这一个，那个文件夹下的好几个文件都需要重构

**Comment by likui628** [comment]
> > @jinmao88我来尝试处理下吧
> 
> 不止这一个，那个文件夹下的好几个文件都需要重构

这个我晓得

**Comment by likui628** [comment]
@jinmao88 还没有完成，只是暂时把菜单和内容显示出来了
